#!/bin/sh

set -e

if test ! -n "${INPUT_FILES}"; then
    echo "No 'files' input was specified"
    exit 1
fi

if test ! -n "${INPUT_CMD}"; then
    echo "No 'cmd' input was specified"
    exit 1
fi

PROMTOOL_ACTION_FILES=${INPUT_FILES}
PROMTOOL_ACTION_COMMAND=${INPUT_CMD}

main() {
    eval promtool "${PROMTOOL_ACTION_COMMAND}" rules "${GITHUB_WORKSPACE}/${PROMTOOL_ACTION_FILES}"
}

main "$@"
