#!/bin/sh

set -e

if test ! -n "${INPUT_PROMTOOL_FILES}"; then
    echo "No 'promtool_files' input was specified"
    exit 1
fi

if test ! -n "${INPUT_PROMTOOL_COMMAND}"; then
    echo "No 'promtool_command' input was specified"
    exit 1
fi

PROMTOOL_ACTION_FILES=${INPUT_PROMTOOL_FILES}
PROMTOOL_ACTION_COMMAND=${INPUT_PROMTOOL_COMMAND}

main() {
    eval promtool "${PROMTOOL_ACTION_COMMAND}" rules "${GITHUB_WORKSPACE}/${PROMTOOL_ACTION_FILES}"
}

main "$@"
